apiVersion: batch/v1
kind: Job
metadata:
  name: xai-benchmark
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: xai-benchmark
    spec:
      restartPolicy: "Never"
      containers:
        - name: xai-benchmark
          image: registry.datexis.com/bvanaken-shk/xai-benchmark:v1.0
          imagePullPolicy: "Always"
          ports:
            - name: client-port
              containerPort: 6006
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: "4Gi"
              cpu: "500m"
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPU
              memory: 28Gi
              cpu: "4000m"
          volumeMounts:
            - name: outcome-paper-models-pvc
              mountPath: "/xai-benchmark"
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          command:
            - /bin/sh
            - "-c"
            - "python interpret_grads_occ.py --models_dir /xai-benchmark/checkpoint_random.pt --output_dir '/xai-benchmark/saliency_random/' --model trans --dataset snli --no_time --dataset_dir data/e-SNLI/dataset --saliency guided sal inputx occlusion"

      nodeSelector:
        gpu: v100
      imagePullSecrets:
        - name:  private-registry-auth
      volumes:
      - name: outcome-paper-models-pvc
        persistentVolumeClaim:
          claimName: outcome-paper-models-pvc