apiVersion: batch/v1
kind: Job
metadata:
  name: randomtransformer
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: randomtransformer
    spec:
      restartPolicy: "Never"
      containers:
        - name: randomtransformer
          image: registry.datexis.com/bvanaken-shk/xai-benchmark:v1.0
          imagePullPolicy: "Always"
          ports:
            - name: client-port
              containerPort: 6006
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: "4Gi"
              cpu: "500m"
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPU
              memory: 28Gi
              cpu: "4000m"
          volumeMounts:
            - name: outcome-paper-models-pvc
              mountPath: "/xai-benchmark"
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          command:
            - /bin/sh
            - "-c"
            - "python train_transformers.py --lr 2e-5 --model_path '/xai-benchmark/checkpoint_random.pt' --gpu --init_only"
      nodeSelector:
        gpu: v100
      imagePullSecrets:
        - name:  private-registry-auth
      volumes:
      - name: outcome-paper-models-pvc
        persistentVolumeClaim:
          claimName: outcome-paper-models-pvc